apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-deployment
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: docker_image
        ports:
        - containerPort: 8080
